services:
  postgres:
    image: 'postgres:17'
    container_name: chess-db
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=chess'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=peaceful'
      - 'POSTGRES_INITDB_ARGS=-c client_encoding=UTF8'
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: