spring.application.name=demo
#
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false
#
spring.datasource.url=jdbc:postgresql://localhost:5433/chess
spring.datasource.username=peaceful
spring.datasource.password=secret
#
spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
app.broadcast.discovery.url=https://lichess.org/api/broadcast
broadcast.discovery.interval=10000
spring.jackson.deserialization.fail-on-unknown-properties=false
#
# Set thread pool size to 4 to allow concurrent execution of scheduled tasks
spring.task.scheduling.pool.size=4
#
logging.level.com.example.demo=DEBUG
logging.level.com.example.demo.broadcast=DEBUG
