spring.application.name=demo
#
spring.batch.jdbc.initialize-schema=always
#spring.batch.job.enabled=false
spring.threads.virtual.enabled=true
#
spring.datasource.url=jdbc:postgresql://localhost:5433/chess
spring.datasource.username=peaceful
spring.datasource.password=secret
#
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true