spring.application.name=demo
#
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false
#
spring.datasource.url=jdbc:postgresql://localhost:5433/chess
spring.datasource.username=peaceful
spring.datasource.password=secret
#
spring.jpa.hibernate.ddl-auto=update
app.broadcast.discovery.url=https://lichess.org/api/broadcast
broadcast.discovery.interval=10000
spring.jackson.deserialization.fail-on-unknown-properties=false
logging.level.com.example.demo=DEBUG
logging.level.com.example.demo.broadcast=DEBUG
